# It could be named any name .yml, not only action
name: 'My Composite Action'
description: 'My composite action description'

inputs:
  input-parameter:
    description: 'A sample input parameter'
    required: true
    default: 'Default value if not provided'

outputs:
  output-parameter:
    description: 'A sample output parameter'

runs:
  using: 'composite'
  steps:
    - name: Step 1
      run: echo "This is Step 1. Input: ${{ inputs.input-parameter }}"
    - name: Step 2
      run: echo "This is Step 2."
    - name: Step 3
      run: echo "This is Step 3."
      continue-on-error: true
