# It could be named any name .yml, not only action
name: 'Composite Runner'
description: 'Repo and vars'

inputs:
  ARTIFACT_NAME:
    description: 'A sample input parameter'
    required: true
    default: 'Default value if not provided'

outputs:
  output-parameter:
    description: 'A sample output parameter'

runs:
  using: 'composite'  
  steps:
   # - name: Download artifacts
   #   uses: actions/download-artifact@v2
   #   with:
   #     name: ${{ inputs.ARTIFACT_NAME }}
    - name: print ARTIFACT_NAME var
      shell: bash
      run: echo ${{ inputs.ARTIFACT_NAME  }}    
    
    - name: Check file structure in the reusable workflow
      shell: bash
      run: ls -lha
